fix(includes): add base_node_rpc.proxy explicitly
Since the `base_node_rpc.proxy` is module is not imported by
`base_node_rpc.__init__`, it is not included by the automatic `py2exe`
module finder. As of 83366cd8bf0673ea6123c541a18897ef457ace52 (i.e.,
v0.2.3), `base-node-rpc` was added as an explicit full package to ensure
that the `base_node_rpc.proxy` was included. However, in recent versions
of the `base-node-rpc` package using `asyncio`, this causes issues with
`py2exe`, e.g.:

```python
Traceback (most recent call last):
  File ".\setup.py", line 39, in <module>
    for p in ph.path('src').walkfiles()])))
  File "C:\Miniconda\envs\microdrop-exe\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Miniconda\envs\microdrop-exe\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Miniconda\envs\microdrop-exe\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Miniconda\envs\microdrop-exe\lib\site-packages\py2exe\build_exe.py", line 243, in run
    self._run()
  File "C:\Miniconda\envs\microdrop-exe\lib\site-packages\py2exe\build_exe.py", line 296, in _run
    self.find_needed_modules(mf, required_files, required_modules)
  File "C:\Miniconda\envs\microdrop-exe\lib\site-packages\py2exe\build_exe.py", line 1342, in find_needed_modules
    mf.import_hook(package, None, ["*"])
  File "C:\Miniconda\envs\microdrop-exe\lib\site-packages\py2exe\mf.py", line 719, in import_hook
    return Base.import_hook(self,name,caller,fromlist,level)
  File "C:\Miniconda\envs\microdrop-exe\lib\site-packages\py2exe\mf.py", line 141, in import_hook
    self.ensure_fromlist(m, fromlist)
  File "C:\Miniconda\envs\microdrop-exe\lib\site-packages\py2exe\mf.py", line 228, in ensure_fromlist
    self.ensure_fromlist(m, all, 1)
  File "C:\Miniconda\envs\microdrop-exe\lib\site-packages\py2exe\mf.py", line 233, in ensure_fromlist
    raise ImportError, "No module named " + subname
ImportError: No module named base_node_rpc._async_py36
```

In this commit, rather than requiring `base-node-rpc` as a full package,
instead add `base_node_rpc.proxy` as an explicitly included module.